package httpclient

// Generated by https://quicktype.io

type Postman struct {
	Info Info   `json:"info"`
	Item []Item `json:"item"`
}

type Info struct {
	PostmanID string `json:"_postman_id"`
	Name      string `json:"name"`
	Schema    string `json:"schema"`
}

type Item struct {
	Name     string     `json:"name"`
	Request  Request    `json:"request"`
	Response []Response `json:"response"`
}

type Request struct {
	Method string          `json:"method"`
	Header []RequestHeader `json:"header"`
	Body   Body            `json:"body"`
	URL    URL             `json:"url"`
}

type Body struct {
	Mode       string     `json:"mode"`
	Raw        string     `json:"raw"`
	Options    Options    `json:"options"`
	Urlencoded []KeyValue `json:"urlencoded"`
	Graphql    Graphql    `json:"graphql"`
}

type Graphql struct {
	Query     string `json:"query"`
	Variables string `json:"variables"`
}

type Options struct {
	Raw Raw `json:"raw"`
}

type Raw struct {
	Language string `json:"language"`
}

type RequestHeader struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	Type  string `json:"type"`
}

type URL struct {
	Raw      string     `json:"raw"`
	Protocol string     `json:"protocol"`
	Host     []string   `json:"host"`
	Port     string     `json:"port"`
	Path     []string   `json:"path"`
	Query    []KeyValue `json:"query"`
}

type Response struct {
	Name                   string           `json:"name"`
	OriginalRequest        Request          `json:"originalRequest"`
	Status                 string           `json:"status"`
	Code                   int64            `json:"code"`
	PostmanPreviewlanguage string           `json:"_postman_previewlanguage"`
	Header                 []ResponseHeader `json:"header"`
	Cookie                 []interface{}    `json:"cookie"`
	Body                   string           `json:"body"`
}

type ResponseHeader struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
